services:
  front:
    build: ./traque-front
    restart: always
  
  reverse_proxy:
    build: ./proxy
    ports:
      - "3000:443"
    volumes:
      - ./traque-back/ssl:/etc/nginx/ssl:ro
    restart: always

  back:
    build: ./traque-back
    ports:
      - "3001:3001"
    restart: always