services:
  front:
    build: ./traque-front
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SOCKET_HOST = 'quentinrsl.com'
      - NEXT_PUBLIC_SOCKET_PORT = 3001

  back:
    build: ./traque-back
    ports:
      - "3001:3001"
    environment:
      - HOST = 'quentinrsl.com'
      - PORT = 3001
      - SSL_KEY = "/etc/letsencrypt/live/quentinrsl.com/privkey.pem"
      - SSL_CERT = "/etc/letsencrypt/live/quentinrsl.com/cert.pem"
      - ADMIN_PASSWORD = 'admin'
      - MAX_PENALTIES = 3
      - ALLOWED_TIME_OUT_OF_ZONE_IN_MINUTES = 10
      - ALLOWED_TIME_BETWEEN_POSITION_UPDATE_IN_MINUTES = 10